/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.*;

public class Library {

    public boolean someLibraryMethod() {
        return true;
    }

    public static int [] roll(int n){
        if(n<0){
            n=0;
        }
        int [] Dice=new int[n];
        Random rn = new Random();

        for (int i=0;i<Dice.length;i++){
            int rand=rn.nextInt(6 - 1 + 1) + 1;
            Dice[i]=rand;
        }
        return Dice;
    }

    public static boolean containsDuplicates(int[]test){
        boolean result=false;
        for (int i = 0; i < test.length; i++) {
            int count=0;
            for (int x = 0; x < test.length; x++) {
                if (test[i]==test[x]){
                    ++count;
//                   System.out.println(count);
                    if (count==2){
                        result=true;
                        return result;
                    }
                }else {
//                   System.out.println("hi");
                    result=false;
                }
            }
        }


        return result;
    }

    public static double calculatingAverages (int[]test){
        double avg=0;
        for (int i : test) {
            avg+=i;
        }
        return avg/test.length;
    }

    public static int[] arrayAvg(int[][]test){
        double low=calculatingAverages(test[0]);
        int idx=0;
        for (int i = 0; i < test.length; i++) {
            if(low>calculatingAverages(test[i])){
                low=calculatingAverages(test[i]);
                idx=i;
            }
        }
        return test[idx];
    }

    public static String Maps(int[][] arr){
        HashSet<Integer> hs= new HashSet<Integer>();
        int size=0;
        int min=arr[0][0];
        int max=arr[0][0];
        for (int[] inner : arr) {
            for (int i : inner) {
                hs.add(i);
                size++;
                if (min>i){
                    min=i;
                }
                if(i>max){
                    max=i;
                }
            }
        }
        String result="High:"+max+" "+"Low:"+min+" ";

        System.out.println("High:"+max);
        System.out.println("Low:"+min);
        for (int i=min;i<=max;i++){
            if (hs.contains(i)==false){
                result+="Never saw temperature: "+i+" ";
                System.out.println("Never saw temperature: "+i);
            }
        }
        return result;
    }

    public static String tally(List<String> testlist){
        String name="";
        int maxVotes=0;
        HashMap<String, Integer> votes=new HashMap<String,Integer>();

        for (String s : testlist) {
            if(! votes.containsKey(s)){
                votes.put(s,1);
            }else {
                votes.put(s,votes.get(s)+1);
            }
        }
        for (Map.Entry<String,Integer> entry:votes.entrySet()){
            if(entry.getValue()>maxVotes){
                maxVotes=entry.getValue();
                name=entry.getKey();
            }
        }
        return name;
    }


}
